services:
  mysql:
    image: mysql:latest 
    restart: unless-stopped
    container_name: mysql
    env_file: .env 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - netcontrol_db_data:/var/lib/mysql 
volumes:
  netcontrol_db_data:


